# Generated by Django 5.2.7 on 2025-10-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_accessrule_businesselement_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrule',
            old_name='delete_permission',
            new_name='delete_own_permission',
        ),
    ]
