# Generated by Django 5.2.7 on 2025-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_rename_delete_permission_accessrule_delete_own_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='email@test.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
